services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/code/public
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
        - app-network

  php:
    build: .
    volumes:
      - ./:/code
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-guestbook}
        # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:


